services:
  postgres:
    image: ankane/pgvector
    container_name: rag_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass
      POSTGRES_DB: ragdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: